### ISSUE TITLE
Incorrect repository name

### ISSUE THREAD

**Issue by volodymyrdovhan** [sokunthearithmakara/mod_interactivevideo#21]
Hello,
based on the naming convention for Moodle plugins, the repository name should match the pattern: `moodle-{plugintype}_{pluginname}`.
For guidance, you can refer to the following documentation:
[Code repository name](https://moodledev.io/general/community/plugincontribution/checklist#code-repository-name)
This is not a strong requirement, just an option to provide a consistent experience for other Moodle developers.

**Comment by sokunthearithmakara** [comment]
@volodymyrdovhan could you please provide an example of the incorrect use of the repository name in this plugin?

**Comment by volodymyrdovhan** [comment]
Hello @sokunthearithmakara,
based on the current repository, it should be renamed as https://github.com/sokunthearithmakara/**moodle-mod_interactivevideo**
However, this is not a requirement and not a blocker for approval.

**Comment by sokunthearithmakara** [comment]
@volodymyrdovhan Ah, got you! Thank you for your clarification!
