### ISSUE TITLE
Rename styles.css to styles.scss

### ISSUE THREAD

**Issue by eduardokraus** [sokunthearithmakara/mod_interactivevideo#8]
Rename styles.css to styles.scss, and the CSS file will be 100%.

https://github.com/sokunthearithmakara/mod_interactivevideo/blob/main/styles.css#L38-L47

see https://github.com/test-moodle/mod_interactivevideo/commit/c326d08a84fc4ba87a21788f4cfb8a7976a47e5f

**Comment by eduardokraus** [comment]
https://github.com/sokunthearithmakara/mod_interactivevideo/blob/main/plugins/inlineannotation/styles.css

**Comment by eduardokraus** [comment]
I didn't call him random. What I noticed is that he has SASS commands inside.

https://github.com/sokunthearithmakara/mod_interactivevideo/blob/main/styles.css#L38-L47

**Comment by sokunthearithmakara** [comment]
What I meant is that you can't just rename styles.css to styles.scss. Moodle looks for styles.css files in all plugin folders to compile and cache.
Also, the snippet you highlighted isn't sass. It's called CSS nesting. It's supported by all browsers and doesn't require any CSS pre-processor. I tested this plugin extensively in Chrome, Edge, Safari and Firefox. Let me know if you experience any issues on your end.

**Comment by eduardokraus** [comment]
Line 38 of your file refers to a SASS/SCSS file (https://sass-lang.com/). To compile it correctly, you need to rename it to .scss or .sass and use a SASS-compatible software to generate the corresponding CSS file.

In the following commit (https://github.com/test-moodle/mod_interactivevideo/commit/c326d08a84fc4ba87a21788f4cfb8a7976a47e5f), I did exactly that, and the generated file is now 100% valid as a .css file.

This new style.css file will be correctly loaded by Moodle.
